# Soft_max_function <hr/>
Neural networks are available for both regression and classifications

In general, using identity function for Regression and soft max function for classification

identity function outputs the input as it is. 

The expression for soft max function is: 

![soft_max_function1](./soft_max_function1.png)
 
exp means exponential function

### OK, Let's implement a soft max function.

In [86]:
import numpy as np

In [87]:
a = np.array([0.3, 2.9, 4.0])
exp_a = np.exp(a) 
print(exp_a)

sum_exp_a = np.sum(exp_a)
print(sum_exp_a)

y = exp_a / sum_exp_a
print(y)

[ 1.34985881 18.17414537 54.59815003]
74.1221542101633
[0.01821127 0.24519181 0.73659691]


pretty easy isn't it?, Let's recreate it as a function.

In [88]:
def softmax(a):
    exp_a = np.exp(a)
    sum_exp_a = np.sum(exp_a)
    return exp_a / sum_exp_a

it's perfect showing soft max function expression 

but there is one problem, overflow !

As you can see, softmax uses exponential functions, but exponential functions outputs very large numbers.

so, we need recreate it 

![soft_max_function2](./soft_max_function2.png)

i will show you one of example with the problem

In [89]:
a = np.array([1010., 1000., 990.])
np.exp(a) / np.sum(np.exp(a))

C:\Users\che99\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: overflow encountered in exp
  
C:\Users\che99\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


array([nan, nan, nan])

you see? there is no number because overflow 

you wanna fix it ?

In [90]:
a = np.array([1010., 1000., 990.])
a = a - np.max(a)
np.exp(a) / np.sum(np.exp(a))

array([9.99954600e-01, 4.53978686e-05, 2.06106005e-09])

it's so easy , you just subtract the maximum number of inputs.

Let's reimplement a soft max function.

In [91]:
def softmax(a):
    a = a - np.max(a)
    exp_a = np.exp(a)
    sum_exp_a = np.sum(exp_a)
    return exp_a / sum_exp_a

In [92]:
test = np.array([1010,1000,990])
softmax(test)

array([9.99954600e-01, 4.53978686e-05, 2.06106005e-09])

### Let's look at the characteristics of soft maxfunction.

In [93]:
a = np.array([3.3, 2.2, 4.8, 7.7, 1,5])
y = softmax(a)
print('after soft max :', y)

sum = 0
for i in y:
    sum += i
print('sum of outputs : ', sum)

after soft max : [0.01077126 0.00358544 0.04827345 0.87732862 0.00107991 0.05896132]
sum of outputs :  1.0


you realized? 'Soft maximum function' always outputs between 0 and 1

and the sum of all the outputs is always 1

we can think outpus are percentage because that characteristics 

you can interpret it as follows.

In [94]:
a = np.array([8.4, 6.8, 8.9])
result = softmax(a)

for i in range(3):
    print('{}: {:.3f} %'.format(i, result[i]* 100 ))

0: 35.080 %
1: 7.083 %
2: 57.837 %
