# Gradient in Neural Network<hr>

We also need to get a gradient from neural network training, the gradient here is
gradient of the cost function for the weight value.<br>
If there is a neural network with a weight of W and a cost function of L and size of 2 x 3, in this case, the gradient can be expressed as \\(\frac{\partial L}{\partial W}\\)<br>
Here is the fomula
![gradient_in_neural_net](./images/gradient_in_neural_net.PNG)

It can be implemented as follows

In [3]:
import sys, os
sys.path.append(os.pardir)
import numpy as np
from common.functions import softmax, cross_entropy_error
from common.gradient import numerical_gradient

In [18]:
class simpleNet:
    def __init__(self):
        self.W = np.random.randn(2,3)
        
    def predict(self, x):
        return np.dot(x, self.W)
    
    def loss(self, x, t):
        z = self.predict(x)
        y = softmax(z)
        loss = cross_entropy_error(y, t)
        
        return loss       

In [22]:
net = simpleNet()
print(net.W)

x = np.array([0.6, 0.9])
p = net.predict(x)
print(p)

np.argmax(p)

t = np.array([0, 0, 1]) # correct list
net.loss(x, t)

[[ 1.28871095  0.92832209 -2.25996271]
 [ 0.45573205  0.78411255  1.1170273 ]]
[ 1.18338541  1.26269454 -0.35065306]


2.366164428331534

Let's get gradients

In [24]:
def f(W):
    return net.loss(x, t)

dW = numerical_gradient(f, net.W)
print(dW)

# also can be used like this 
# f = lambda w: net.loss(x, t)
# dW = numerical_gradient(f, net.W)

[[ 0.26107339  0.28262211 -0.5436955 ]
 [ 0.39161009  0.42393316 -0.81554325]]


There are \\(\frac{\partial L}{\partial W} \\)<br>
The \\(\frac{\partial L}{\partial W_{11}} \\) is alomost 0.2 this mean, if you increase \\(W_{11}\\) by h, the value of the loss function increases by 0.2h<br>
And the \\(\frac{\partial L}{\partial W_{13}}\\) is almost -0.5 this mean if you increase \\(W_{13}\\) by h, the value of the loss function decreases by 0.5h<br>